microcks/microcks

src/main/java/io/github/microcks/util/openapi/OpenAPIImporter.java, src/test/resources/io/github/microcks/util/openapi/cars-openapi-with-json.yaml
Resolves #132 
The OpenAPI version is checked before the OpenAPIImporter is instantiated, so it is known to be valid. Additionally, the presence of quotations in the spec causes uploads to report successfully despite the absence of a mocked server. It looks like this is probably due to a file pointer overrun where isYaml remains null, though this has not been verified.
=> Remove the OpenAPI version check at importer instantiation time

src/main/java/io/github/microcks/util/postman/PostmanCollectionImporter.java
This PR fixes two things:
- #147: Postman examples with empty response body generates a mock that returns null
- Postman examples without http status (the author implied "200 OK" ?) generate a deficient mock
Before:
```raw
$ curl -D - -XPOST http://localhost:8080/rest/Test/1.0/test
HTTP/1.1 200 
X-Application-Context: application
Content-Type: text/plain;charset=UTF-8
Content-Length: 4
Date: Wed, 08 May 2019 11:08:12 GMT
null
```
After:
```raw
$ curl -D - -XPOST http://localhost:8080/rest/Test/1.0/test
HTTP/1.1 200 
X-Application-Context: application
Content-Type: text/plain;charset=UTF-8
Content-Length: 4
Date: Wed, 08 May 2019 11:08:12 GMT
```
Before:
```raw
$ curl -D - http://localhost:8080/rest/Test/1.0/test
HTTP/1.1 500 
X-Application-Context: application
Content-Type: …
```
=> Handle empty bodies in postman collection + default status code

src/main/java/io/github/microcks/util/openapi/OpenAPIImporter.java
Currently, when saving spec body, no encoding was specified. So the spec may be saved in wrong encoding.
=> Spec body should also use UTF8 encoding

install/podman-compose/.gitignore, install/podman-compose/config, install/podman-compose/keycloak-realm/microcks-realm-sample.json, install/podman-compose/microcks-template-rootless.yml, install/podman-compose/microcks-template.yml, install/podman-compose/run-microcks.sh
Hi !
This PR is about running Microcks on Linux with podman. 
To make it work, I had to:
- create a dedicated folder for the mongodb volume (podman does not create a folder automatically if it does not exist)
- change the volumes to add the "z" flag to ask podman [to fix SELinux labels for us](http://docs.podman.io/en/latest/markdown/podman-run.1.html)
> To change a label in the container context, you can add either of two suffixes :z or :Z to the volume mount. These suffixes tell Podman to relabel file objects on the shared volumes. The z option tells Podman that two containers share the volume content. As a result, Podman labels the content with a shared content label. Shared volume labels allow all containers to read/write content. 
- provide two podman-compose templates (one for …
=> Initial support for running Microcks with Podman

webapp/src/main/java/io/github/microcks/web/KeycloakConfigController.java, webapp/src/main/resources/config/application.properties
should fix #119 
Change the `/api/keycloak` service to use the `external_url` configuration instead of the main keycloak if `KEYCLOAL_EXTERNAL_URL` is set. If not, then fallback to the same config as the backend services.
=> use external value if available, otherwise use same

install/podman-compose/config, install/podman-compose/microcks-template-rootless.yml, install/podman-compose/microcks-template.yml
The podman-compose files were broken due to a dangling "config" symlink (removed from docker-compose)
=> Fix podman-compose (missing config volume)

webapp/src/main/java/io/github/microcks/web/SoapController.java
This fix does a simple check to see if the request Content-Type was SOAP 1.2 based and returns that Content-Type value if true.  It assumes the creator of the Mock SOAP service has used the correct SOAP envelope namespace value to match the response type (1.1="xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/", 1.2=xmlns:soap="http://www.w3.org/2003/05/soap-envelope").
It would be helpful if the SoapUI instructions included a paragraph about the above + some other things I had to discover the hard way (e.g. SoapUI script dispatching needs to return a specific response and cannot use scripting to throw an error; when looking for an attribute name, you have to use the namespace value if present)
=> Handle SOAP 1.2 requests (Issue #356)

.gitignore, commons/model/src/main/java/io/github/microcks/domain/EventMessage.java, minions/async/src/main/java/io/github/microcks/minion/async/producer/KafkaProducerManager.java, minions/async/src/main/java/io/github/microcks/minion/async/producer/MQTTProducerManager.java, minions/async/src/main/java/io/github/microcks/minion/async/producer/ProducerManager.java, webapp/src/main/java/io/github/microcks/util/asyncapi/AsyncAPIImporter.java, webapp/src/main/java/io/github/microcks/web/TestController.java, webapp/src/main/webapp/src/app/models/service.model.ts, webapp/src/main/webapp/src/app/pages/services/{serviceId}/service-detail.page.ts, webapp/src/main/webapp/src/app/services/tests.service.ts
Uses examples given in schema definition for channel parameters  to replace placeholders in topic string.
Implemented in app (the mock urls/topics displayed for each sample message) and also in the minion's AsyncAPI Producer.
See - MQTT Topic in this screenshot - 
Also - an example AsyncAPI file for testing attached:
[api-maintenance.async-api-spec.txt](https://github.com/microcks/microcks/files/6265538/api-maintenance.async-api-spec.txt)
=> Add topic channel substitution parameters for AsyncAPI

install/docker-compose/README.md, install/docker-compose/keycloak-realm/microcks-realm-sample.json
change the docker-compose user's password to use the same as the operator.
=> Use same password as operator install

install/kubernetes/README.md, install/kubernetes/microcks/README.md, install/kubernetes/microcks/templates/service.yaml, install/kubernetes/microcks/values.yaml
This PR should allow people to override the Service type of microcks and keycloak, if they need to, without cloning the code (i.e. following [the helm installation instructions](https://microcks.io/documentation/installing/kubernetes/#helm-3)). The helm install command would look like:
`helm install microcks microcks/microcks —-version 1.1.0 --namespace microcks --set microcks.url=microcks.$(minikube ip).nip.io --set keycloak.url=keycloak.$(minikube ip).nip.io  --set microcks.serviceType=NodePort --set keycloak.serviceType=NodePort`
This should address https://github.com/microcks/microcks/issues/450
=> Allow service type override on helm install

install/podman-compose/microcks-template-rootless.yml, install/podman-compose/microcks-template.yml, install/podman-compose/run-microcks.sh
This PR is enabling support for podman-compose 1.x.
Since podman-compose v1.0, the --transform_policy option is not accepted anymore and at the same time, not needed anymore.
=> Fix podman-compose support

install/docker-compose/docker-compose.yml
The current compose fails to launch Keycloak as the entrypoint script expects the "DB_ADDR" environment variable to be set, and then defaults to trying to connect to Postgres. The in-memory database h2 is used instead of running another container with Postgres.
=> Set Keycloak DB to h2 when using docker-compose

webapp/README.md, webapp/pom.xml, webapp/src/main/java/io/github/microcks/util/graphql/GraphQLTestRunner.java, webapp/src/main/java/io/github/microcks/util/openapi/OpenAPITestRunner.java
@lbroudoux a very small contribution, but it would have helped me a lot to get up and running on my local devenv.
The dependency excludes are required to satisfy eclipse, which was reporting stuff like:
`The package org.w3c.dom is accessible from more than one module: <unnamed>, java.xml` 
in my tests everything worked still fine.
I made separate commits if you don't like all the changes...
Note: I was not able to get it to work with a local keycloak installation, therefore my update in the README.
=> Dependency management cleaning + little changes

install/docker-compose/README.md
image: jboss/keycloak:14.0.0 does not work when installing locally on arm64/M1 machine. Changing it to image which supports arm64 works fine. (image: wizzn/keycloak:14 supports arm64/M1 chips)
=> Added README note for installing Microcks on arm64/M1 machine

install/docker-compose/docker-compose-osx-m1.yml, install/docker-compose/docker-compose-with-proxy.yml, install/docker-compose/docker-compose.yml
- used import-realm that can import the json realm file automatically from the /opt/keycloak/data/import folder while starting up
- The earlier solution also worked but the new one is straightforward
=> chore: use import realm startup argument instead of using a custom script to import realm

webapp/src/main/java/io/github/microcks/web/GraphQLController.java, webapp/src/test/java/io/github/microcks/web/GraphQLControllerIT.java
- GraphQL - Allows querying multiple distinct operations without aliases
Resolves #801
=> fix #801: GraphQL multi-queries of different operations throws exception

api/microcks-openapi-v1.7.yaml
Some fields of OpenAPI v1.7 schema are wrong
Fixes:
- Additional properties of `CounterMap` (it's a `number`)
- `public-client` of `KeycloakConfig` component returns a boolean, not a string
=> fix: OpenAPI v1.7 schema

webapp/src/main/java/io/github/microcks/util/soapui/XmlHolder.java, webapp/src/test/java/io/github/microcks/util/soapui/XmlHolderTest.java
I added three tests to query the XmlHolder class. They pass when using the SOAPUI implementation.
I fixed the microcks implementation to handle that cases.
#884
=> Handle namespace in XPATH as soapui xmlHolder does

install/kubernetes/microcks/templates/ingress.yaml, install/kubernetes/microcks/values.yaml
This PR adds the 'ingressClassName' field to the spec property of the ingress yaml. It will allow to specify a custom ingress directly in the property rather than using the annotation.
The chart was tested with and without the ingressClassesName and it works as expected.
*Example shows microcks-grpc ingress without ingressClassName set and microcks-keycloak with ingressClassName added*
=> Add ingressClassName property

webapp/src/main/java/io/github/microcks/util/AbsoluteUrlMatcher.java, webapp/src/main/java/io/github/microcks/web/RestController.java, webapp/src/test/java/io/github/microcks/util/AbsoluteUrlMatcherTest.java
Microcks overrides the Location header when a absolute URL is set.
```yaml
openapi: "3.0.0"
info:
title: Simple API overview
version: 2.0.0
paths:
/:
get:
responses:
'301':
description: |-
redirect
headers:
Location:
schema:
type: string
examples:
foo: 
value: "http://www.google.com"
content:
text/html:
examples: 
foo:
value: ""
```
Microcks Response:
```
http://localhost:8080/rest/Simple+API+overview/2.0.0/
Host: localhost:8080
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
DNT: 1
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document …
```
=> fix: Location override with absolute url

webapp/src/main/java/io/github/microcks/util/GitLabReferenceURLBuilder.java
When importing from gitlab the code fails when trying to get the filename as there is a null key in the Headers
=> fix: add null check to getFileName

README.md, commons/util/src/main/java/io/github/microcks/util/openapi/OpenAPISchemaValidator.java, commons/util/src/test/java/io/github/microcks/util/openapi/OpenAPISchemaValidatorTest.java, commons/util/src/test/resources/io/github/microcks/util/openapi/nullable-fields-openapi.yaml
- Added a step to parse the $ref component as well as the models
- Added a test to make sure that component having a nullable field won't make the json schema validator chash the api test
Fixes #995
=> $ref component not being parsed in json schema causing issue with nullable field

install/kubernetes/README.md, install/kubernetes/microcks/templates/NOTES.txt, install/kubernetes/microcks/templates/claim.yaml, install/kubernetes/microcks/templates/configmap.yaml, install/kubernetes/microcks/templates/deployment.yaml, install/kubernetes/microcks/templates/ingress.yaml, install/kubernetes/microcks/templates/secret.yaml, install/kubernetes/microcks/templates/service.yaml, install/kubernetes/microcks/values.yaml
In the context of local kubernetes deployment installed on laptop, mickrocks helm allow_disable_keycloak_in_helm_charts offers the possibility to bypass the keycloak installation and use microcks without any authentication mechanism
Fixes #1001
=> Allow keycloak-less kubernetes installation

webapp/src/main/java/io/github/microcks/web/SoapController.java
Return an explicit message when an error occurs while mocking soap response
Note : The error message is returned as the response body like others. Using Spring exception handler may be more appropriate.
#895
=> Add explicit error message (SOAP response)

webapp/src/main/java/io/github/microcks/config/WebConfiguration.java, webapp/src/main/java/io/github/microcks/web/filter/DynamicOriginCorsFilter.java
This PR adds dynamic cors handeling to microcks rest endpoints.
It takes the request made to microcks and returns the cors headers generated with the request's origin header.
If that header is not found it uses a default value.
Testing:
Go to https://microcks.io/ in your browser. Do a fetch request in the console to a mock
=> feat: add auto-cors

webapp/src/main/resources/templates/redoc.html
This is an update of the redoc url.
The new documentation specifies another url to use for redoc
```
Add an HTML element to the page
Create an HTML page, or edit an existing one, and add the following within the body tags:
<redoc spec-url="http://petstore.swagger.io/v2/swagger.json"></redoc>
<script src="https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js"> </script>
```
https://github.com/Redocly/redoc
=> Chore: update redocly

webapp/src/main/java/io/github/microcks/config/WebConfiguration.java, webapp/src/main/java/io/github/microcks/web/filter/DynamicCorsFilter.java, webapp/src/main/java/io/github/microcks/web/filter/DynamicOriginCorsFilter.java, webapp/src/test/java/io/github/microcks/web/filter/DynamicCorsFilterTest.java
DynamicOriginCorsFilter generates CORS responses by coping the Origin from the request to the "Access-Control-Allow-Origin" Header and adding the rest of the CORS headers such as "Access-Control-Allow-Methods", "Access-Control-Max-Age", "Access-Control-Allow-Headers", "Access-Control-Allow-Credentials".
When setting "Access-Control-Allow-Credentials" to "true", "`*`" in "Access-Control-Allow-Headers" is not a wild card and is interpreted as the "`*`" header. So CORS fails when there is a custom header "x-smth" in the request.
Make the "Access-Control-Allow-Headers" dynamic by getting the headers of the request and putting it in "Access-Control-Allow-Headers".
=> DynamicOriginCorsFilter Overhaul

webapp/src/main/java/io/github/microcks/web/filter/DynamicCorsFilter.java, webapp/src/test/java/io/github/microcks/web/filter/DynamicCorsFilterTest.java
When doing CORS request, we can send a header("Access-Control-Request-Headers") to request specific headers.
This PR implements this additional generation in the DynamicCorsFilder
#
=> Add missing headers for DynamicCorsFilter

install/kubernetes/microcks/templates/deployment.yaml
HELM CHART Update:
Avoid double directory when adding secrets in Microcks deployment.
=> Fix path to mount secrets on microcks deployments

minions/async/pom.xml, minions/async/src/test/java/io/github/microcks/minion/async/consumer/AMQPMessageConsumptionTaskITest.java
- Add integration test to AMQPMessageConsumptionTaskITest
- Add testcontainers to `microcks-async-minion`
Fixes #1128
=> Add integration tests to AMQPMessageConsumptionTaskITest class

commons/util-el/src/main/java/io/github/microcks/util/el/VariableReferenceExpression.java, commons/util-el/src/test/java/io/github/microcks/util/el/VariableReferenceExpressionTest.java
This PR allows the usage of JSON pointers to array and object contents in templates. These node's contents will be returned as JSON serialized strings and can be used in JSON responses. Also exception handling has been improved to catch exceptions on accessing the JsonNode referenced and returning null in case of an error.
This allows this request:
```
{
"library": "My Personal Library",
"books": [
{ "title":"Title 1", "author":"Jane Doe" },
{ "title":"Title 2", "author":"John Doe" }
]
}
```
to reply with this mock template:
```
{
"allBooks": {{ request.body/books }},
"firstBook": {{ request.body/0 }}
}
```
and will return this response body:
```
{
"allBooks": [{ "title":"Title 1", "author":"Jane Doe" },{ "title":"Title 2", "author":"John Doe" }],
"firstBook": { "title":"Title 1", …
```
=> Allow JSON pointers to array and object contents in templates

webapp/src/main/java/io/github/microcks/util/openapi/OpenAPIImporter.java, webapp/src/test/java/io/github/microcks/util/openapi/OpenAPIImporterTest.java, webapp/src/test/resources/io/github/microcks/util/openapi/object-query-params.yaml
- Add support for object query parameters as the openAPI specs describe https://swagger.io/docs/specification/serialization/
this only support the default configuration for handling query parameters with `style: form` and `explode: true`
Resolves #1143
=> feat: Add support for object query parameters

webapp/src/main/webapp/src/app/pages/tests/create/test-create.page.css, webapp/src/main/webapp/src/app/pages/tests/create/test-create.page.html, webapp/src/main/webapp/src/app/pages/tests/create/test-create.page.ts, webapp/src/main/webapp/src/app/pages/tests/create/tests.page.spec.ts
Create a 'select all' & 'deselect all' buttons 
Resolves #1153
=> Add "select all" & "deselect all" actions for operations list on test create page

webapp/src/main/webapp/src/app/components/vertical-nav/vertical-nav.component.html, webapp/src/main/webapp/src/app/components/vertical-nav/vertical-nav.component.ts
- Checks when Microcks is using Auth by checking the config service
- If Microcks is not using Auth it removes the user Info with the dropdown
- else if Microcks is using auth it show the user Info
Not using Auth:
Using Auth:
#1138 
- Preferences points to empty url "http://localhost:8080/#0"
- When Keycloak user has no "first Name" or "last Name". Microcks doesn't show a user. 
We could use "prefered_username" in this case
=> fix: disable dropdown and info when in unauthenticated mode

samples/UserSignedUpAPI-asyncapi-googlepubsub.yml, samples/UserSignedUpAPI-asyncapi-nats.yml, samples/UserSignedUpAPI-asyncapi-sns.yml, samples/UserSignedUpAPI-asyncapi-sqs.yml, samples/UserSignedUpAPI-asyncapi.yml
- Migrate AsyncAPI examples in `/samples` to 3.0.0.
- I used a combination of `asyncapi convert` and `asyncapi validate` to convert the examples to 3.0.
To test/validate these changes, I...
1. Converted using `asyncapi convert`.
2. Validated using `asyncapi validate`, and made any updates needed to resolve any issues caught.
3. Compared information side-by-side for the v2 and v4 versions using a local setup of Microcks.
1. Followed the instructions in `CONTRIBUTING.md` to spin up + login.
2. Imported v2 and v3 version of the apis to compare visually. Looked at the mocks + documentation page.
3. Not sure if anything else I could do to validate they _work_ as expected. I’m _assuming_ these aren’t actually testable as they are samples.
Resolves #1152
=> Migrate AsyncAPI `/samples` to 3.0

install/kubernetes/microcks/templates/_helpers.tpl, install/kubernetes/microcks/templates/deployment.yaml, install/kubernetes/microcks/templates/secret.yaml
In an umbrella chart, all named templates of all sub-charts are merged, which can cause unexpected conflicts.
Thus add microcks prefix to prevent conflicts with other sub-charts.
Fixes #1263
=> Prefix named helm templates with microcks

distro/uber/src/main/resources/META-INF/native-image/reflect-config.json
- Registered `graphql.ExecutionResult` class to used by reflection in r`eflect-config.json`.
- After this, we are able to content in response of graphql introspection query
- Fixes #1235
=> GraphQL schema instrospection not working on native distribution

commons/util/src/main/java/io/github/microcks/util/openapi/OpenAPISchemaValidator.java
add a guard on the jsonNode schema path access to prevent testing staying in pending state.
Fixes #1293
=> Add missing guard on jsonNode schema path access

commons/util/src/main/java/io/github/microcks/util/openapi/OpenAPISchemaValidator.java, commons/util/src/test/java/io/github/microcks/util/openapi/OpenAPISchemaValidatorTest.java, commons/util/src/test/resources/io/github/microcks/util/openapi/season-nullable-all-of.yaml
Hello again 😁
The proposed fix adds some behavior in the OpenAPISchemaValidator.convertType() method:
The idea is:
- when we encounter a nullable allOf or anyOf:
we nest their content into a oneOf and add a null type to a branch of the oneOf.
- when we encounter a nullable oneOf:
we just add a null type if it's not already here (because this method is called recursively, this prevents treating the same structure twice)
Resolves #1318
=> fix: #1318 Support nullable on composition structures

commons/util-el/src/main/java/io/github/microcks/util/el/ExpressionParser.java, commons/util-el/src/test/java/io/github/microcks/util/el/ExpressionParserTest.java
- This PR adds support for escape character, which are provided in response example of specification file.
- This PR modifies `skipToCorrectEndSuffix()` method of `ExpressionParser` which now will now return index of last '}}'.
- I will enable us to wrap values inside the wrapper like `{}`, `()`, `##`, `[]` in response body.
- Now Microcks will be able to parse escape characters which are provided in response example of specification file like given below:
```
{
"id": "{{{uuid()}}}",
"name": "#{{ request.body/name }}#"
}
```
- This will generate result like given below:
```
{
"id": "{570e8c11-cac6-42e1-ab3a-6f4e6d9a10a2}",
"name": "#Rusty#"
}
```
**it will support wrappers like '{}', '()', '[]' '##' only.
Fixes #1353
=> Add escape character on dynamic response

webapp/src/main/java/io/github/microcks/web/RestController.java, webapp/src/test/java/io/github/microcks/web/RestControllerIT.java
When using the `PROXY` (or `PROXY_FALLBACK`) dispatcher, any `delay` for the operation was ignored.
None filed.
Pending...
=> fix: Respect operation `delay` when using the `PROXY` dispatcher.

webapp/src/main/java/io/github/microcks/util/metadata/ExamplesImporter.java, webapp/src/test/java/io/github/microcks/util/metadata/ExamplesImporterTest.java, webapp/src/test/resources/io/github/microcks/util/metadata/APIPastry-2.0-examples.yml
- This PR fixes default status issue of APIExample file.
- Initialized response in `ExampleImporter` with default status `200`, so if there is no mention of status in `APIExample` file default status will be used.
Fixes #1439
=> APIExample doesn't provide a default status

webapp/src/main/java/io/github/microcks/util/grpc/GrpcTestRunner.java, webapp/src/main/java/io/github/microcks/util/postman/PostmanTestStepsRunner.java, webapp/src/main/java/io/github/microcks/util/test/HttpTestRunner.java, webapp/src/main/java/io/github/microcks/util/test/TestRunnerCommons.java
- Add headers specified in Requests and Test Run to test invocations
Resolves #1418 
During the implementation, I noticed that all test runners share the same code to collect the headers and refactored it into one method in `TestRunnerCommons`. If that is not wanted, let me know and I can revert this change.
=> #feat: 1418 support headers in grpc tests

webapp/src/main/java/io/github/microcks/util/grpc/GrpcTestRunner.java, webapp/src/test/java/io/github/microcks/web/TestControllerIT.java
- Running a gRPC test suite with failing tests currently leads to a `StatusRuntimeException` being thrown and the test run staying in progress forever
- PR adds logic to catch `StatusRuntimeException` for unsuccessful RPC calls (structured as in `HttpTestRunner`) and store failure results in Test Run
- Failing test run contains message with gRPC status code and error message
**Before**: 
Test run stays `in_progress` forever:
With error in logs: 
**After**: 
Test run finishes and is marked as `failed`. 
Detailed test results show error code and message.
=> fix: finish test run with details about failure if gRPC test suite fails

.github/workflows/build-container.yml, .github/workflows/build-verify.yml
Tests: https://github.com/inosmeet/microcks/actions/runs/13305709368/job/37156118925
This involves some redundant code while parallelizing `integraiton tests` and `javadoc check`.
Fixes: #1488 
cc @lbroudoux @yada
=> ci: optimize build-verify.yml workflow

webapp/src/main/webapp/src/app/pages/services/services.page.ts
- Fixed the bug where the dropdown was showing "For Domain" even when no domain was mentioned in the entries.
- The UI now correctly hides the "For Domain" label and the dropdown when no domain is provided.
- Ensures a cleaner and more intuitive user experience.
-  There is an option to set the "status" field, but it does not appear in the search field.  
Not sure if this is a bug or if search by status is intentionally excluded.
Fixes #1573
=> fix(search_field): fix the dropdown bug when no domain mention in entries

webapp/src/main/webapp/src/lib/patternfly-ng.css, webapp/src/main/webapp/src/styles.css
This PR resolves the UI misalignment issue caused by the unnecessary addition of the `show` class when the dropdown is opened. The `show` class was overriding the default styling (`display: table-cell`) applied to the `.input-group-btn` component, resulting in a broken layout with child elements appearing on multiple lines.
Issue #1584
=> fix: ui alignment for dropdown

.github/workflows/api-check.yml, install/docker-compose/keycloak-realm/microcks-realm-sample.json, testsuite/api-tests.js, testsuite/commons.js, testsuite/flavor-config.js, testsuite/upload-artifacts.sh
Part of: #1480
As it is now, checks related to async-minion will fail.
For `regular-auth` and `regular-noauth` flavors, I'm doing complete healthchecks, which I wonder if it's too much?
cc @lbroudoux
=> feat: add workflow for testing APIs

minions/async/src/main/java/io/github/microcks/minion/async/AsyncAPITestManager.java, minions/async/src/test/java/io/github/microcks/minion/async/AsyncAPITestManagerIT.java, minions/async/src/test/java/io/github/microcks/minion/async/AsyncAPITestManagerTest.java, minions/async/src/test/resources/io/github/microcks/minion/async/send-message-asyncapi-3.0.yaml
- This PR adds support for handling `contentType : <any>` at message level for AsyncAPI tests. 
- Previously, it was expecting `application/json`.
- `io.github.microcks.minion.async.AsyncAPITestManager.AsyncAPITestThread.getExpectedContentType()` was not able to determine message level content type because we were not following `$ref` recursively to identify the actual message node. 
- That's why it was returning `application/json` as content type because it's a default one. 
Fixes #1561
=> Fix: AsyncAPI tests cannot handle contentType `any`

.github/workflows/sonar-cloud-analysis.yml
At best of my understanding Sonar requires access to the `SONAR_TOKEN` secret which is not available on forks for security reasons.
I noticed that some CI jobs are already disabled and made the exclusion consistent with them.
=> Disable not working sonar check on forks

commons/model/src/main/java/io/github/microcks/domain/ParameterLocation.java, webapp/src/main/webapp/src/app/models/service.model.ts, webapp/src/test/java/io/github/microcks/util/openapi/SwaggerImporterTest.java
Adding body as a valid parameter location in both Java and TypeScript enums, preventing IllegalArgumentException when importing Swagger specs with `body` parameters.
Fixes microcks#1763
=> fix: swagger import fail because body parameter is not exist
