microcks/microcks

src/main/java/io/github/microcks/web/RestController.java

The mock is ignoring the accept header of the request, although they are supported by OAS3.0.
With this little change, the response with the matching vendor specific type is returned. If it is not found or not set, the default behavior is executed, return the first one.

Picking mock result based on Accepted content type

---

install/docker-compose/config/features.properties

Fix typo in describing features related properties

---

commons/util-el/src/main/java/io/github/microcks/util/el/ExpressionParser.java
commons/util-el/src/test/java/io/github/microcks/util/el/ExpressionParserTest.java

 handle VariableExpressions with nested XPath functions

---

webapp/src/main/java/io/github/microcks/web/RestController.java
webapp/src/test/java/io/github/microcks/web/RestControllerIT.java
webapp/src/test/resources/io/github/microcks/util/openapi/pastry-with-details-openapi.yaml

fixes https://github.com/microcks/microcks/issues/614

Fallback matcher must not match slashes

---

webapp/src/main/java/io/github/microcks/util/DispatchStyles.java
webapp/src/main/java/io/github/microcks/util/soapui/SoapUIProjectImporter.java
webapp/src/main/java/io/github/microcks/web/SoapController.java
webapp/src/test/java/io/github/microcks/web/SoapControllerIT.java
webapp/src/test/resources/io/github/microcks/util/soapui/HelloService-random-soapui-project.xml

My first one.
If this is ok, I'll do the same for the REST protocol

feat #722: [SOAP] include random dispatch for SoapUI project

---

CONTRIBUTING.md
dev/.gitignore
dev/start-keycloak.sh
dev/start-mongodb.sh
install/kubernetes/microcks/templates/deployment.yaml
webapp/README.md

closes #768 
Use helm value for replicas.

fix(replicas) Fix hard coded replicas value

---

commons/model/src/main/java/io/github/microcks/domain/OAuth2ClientContext.java

https://sonarcloud.io/project/issues?open=AYs4KJjND8nGLtxRKw-r&id=microcks_microcks
- ...
- ...
- ...

fix: Remove unused OAuth2ClientContext constructor

---

commons/model/src/main/java/io/github/microcks/domain/SecretRef.java

https://sonarcloud.io/project/issues?open=AYmZth2nBCcdL_hhQMco&id=microcks_microcks
- ...
- ...
- ...

Fix non-public properties for SecretRef

---

webapp/src/main/java/io/github/microcks/config/WebConfiguration.java
webapp/src/main/java/io/github/microcks/web/RestController.java
webapp/src/main/resources/config/application.properties

Add Origin Configuration for REST mocks
- ...
- ...
- ...
Ref: #956

feat: add configuration for Cors origin

---

commons/model/src/main/java/io/github/microcks/util/IdBuilder.java

Ref: https://sonarcloud.io/project/issues?open=AYmZth3MBCcdL_hhQMcr&id=microcks_microcks
- ...
- ...
- ...

refactor: Add a private constructor to IdBuilder to hide the implicit public one.

---

minions/async/src/main/docker/Dockerfile.legacy-jar
minions/async/src/main/java/io/github/microcks/minion/async/producer/KafkaProducerManager.java

- Add kafka sasl.login.callback.handler.class property support
- Add Dockerfile for quarkus legacy-jar build
- <a href="https://github.com/microcks/microcks/issues/966">#966</a>

feat: kafka login callback handler support

---

webapp/src/main/webapp/src/app/app.module.ts
webapp/src/main/webapp/src/app/pages/services/{serviceId}/_components/exchanges-tabset/exchanges-tabset.component.html
webapp/src/main/webapp/src/app/pages/services/{serviceId}/_components/exchanges-tabset/exchanges-tabset.component.ts
webapp/src/main/webapp/src/app/pages/services/{serviceId}/service-detail.page.html

Extracted <tabset/> section from the component (webapp/src/main/webapp/src/app/pages/services/{serviceId}/service-detail.page) into the exchanges-tabset component (webapp/src/main/webapp/src/app/pages/services/{serviceId}/_components/exchanges-tabset)
Resolves #979

Optimize: Extract Tabset in service view into another component and render only the selected tab

---

benchmark/README.md
benchmark/bench-microcks.js
observability/configs/grafana-datasources.yaml
observability/configs/otel-collector.yaml
observability/configs/tempo.yaml
observability/dashboards/dashboards.yml
observability/dashboards/k6.json
observability/dashboards/microcks-overview.json
observability/start-o11y-dev-stack.sh
observability/teardown-o11y-dev-stack.sh
webapp/pom.xml
webapp/src/main/docker/Dockerfile
webapp/src/main/java/io/github/microcks/config/MicrometerConfiguration.java
webapp/src/main/resources/config/application.properties

- Adds Opentelemetry instrumentation to get logs metrics and traces from Microcks mock services
- Adds a k6 script to load test microcks
- Adds scripts to setup a Grafana, Prometheus, Loki, Tempo & Opentelemetry Collector instance to host telemetry data and dashboards
- Adds Dashboards for microcks services to correlate metrics logs and traces
Implements #870 
Implements #871 
Implements #992

Adding full observability with Opentelemetry to microcks 

---

commons/model/src/main/java/io/github/microcks/util/IdBuilder.java
commons/model/src/main/java/io/github/microcks/util/Sanitizer.java
webapp/src/test/java/io/github/microcks/service/ServiceServiceTest.java

- Implementing solution of replacing invalid with a character here that character is "-"
#1067

Documentation not Rendering with multi-OpenApi files 

---

webapp/src/main/java/io/github/microcks/util/ai/AICopilotHelper.java
webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java
webapp/src/test/java/io/github/microcks/util/ai/AICopilotHelperTest.java

Add prompt generation optimization for generate rest API examples with openai
Resolves #1103

Reduce amount of tokens needed in prompt for creation of rest API examples using openai

---

minions/async/src/test/java/io/github/microcks/minion/async/consumer/AMQPMessageConsumptionTaskIT.java
webapp/src/main/java/io/github/microcks/util/HTTPDownloader.java
webapp/src/main/java/io/github/microcks/web/UploadArtifactController.java
webapp/src/test/java/io/github/microcks/web/AbstractBaseIT.java
webapp/src/test/java/io/github/microcks/web/UploadArtifactControllerIT.java
webapp/src/test/java/io/github/microcks/web/UploadArtifactControllerTest.java

> [!IMPORTANT]
> We need to be careful changing the specification on  samples, because can break those tests.
- Rename `AMQPMessageConsumptionTaskITest` to `AMQPMessageConsumptionTaskIT`
- Add integration test to ÙploadArtifactController`
#1128

Add integration test to UploadArtifactController 

---

webapp/src/main/java/io/github/microcks/util/postman/PostmanCollectionImporter.java

- Added support for postman collection structured versioning.
- Fixes #1297

Add support for Postman Collection structured versioning

---

README.md

Update doc url in readme

---

commons/util-el/src/main/java/io/github/microcks/util/el/function/RandomIntELFunction.java
commons/util-el/src/main/java/io/github/microcks/util/el/function/RandomValueELFunction.java

1/
Fix sonarcloud issue 17/514, Remove this unused import 'java.util.Random': 
https://sonarcloud.io/project/issues?open=AYzu6wu0tM5zpUj8-I6F&id=microcks_microcks
2/
Fix sonarcloud issue 28/1037, Remove this unused import 'java.util.Random': 
https://sonarcloud.io/project/issues?open=AYzu6wumtM5zpUj8-I6E&id=microcks_microcks
#1362

Clean unused import issue from Sonar

---

webapp/src/main/java/io/github/microcks/web/GraphQLController.java

- implements alias support for single GraphQL queries
- no breaking changes
```bash
microcks/webapp on  FEAT-graphql-single-query-alias-support:1.11.x [!⇡] via ☕ v23 on ☁️  (us-east-1) 
❯ curl --location 'http://localhost:8080/graphql/Foo/1.8.0' \
--header 'Content-Type: application/json' \
--data '{"query":"query GetVersionInfo {MyAlias: versionInfo(refId: \"test-single-query-alias\")}","variables":{}}' | jq 
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   183  100    77  100   106    205    282 --:--:-- --:--:-- --:--:--   488
{
"data": {
"MyAlias": {
"versions": [
{
"component": "foo",
"version": "1.8.0"
}
]
}
}
}
microcks/webapp on  FEAT-graphql-single-query-alias-support:1.11.x [!⇡] via ☕ v23 on ☁️ …
```

feat(graphql): impl alias support for single queries

---

webapp/src/main/webapp/src/app/pages/services/{serviceId}/operation/operation-override.page.html

Fix typo in match regexp input label

fix(ui): Fix typo in match regexp input label

---

webapp/src/main/java/io/github/microcks/web/RestController.java

Refactoring to fix sonar lint warnings, mainly complexity issues 
See also #1362

refactor: fix cognitive complexity issues 

---

install/docker-compose/README.md

Update broken link.
Fixes: #1530

fix: broken link in install documentation

---

webapp/pom.xml

fix: add groovy-datetime dependency

---

install/podman-compose/microcks-template-async-addon.yml
install/podman-compose/microcks-template-devmode.yml
install/podman-compose/microcks-template.yml

Add healthchecks for all podman compose files

feat: add healthcheck for podman-compose installation

---

install/docker-compose/docker-compose-async-addon.yml
install/docker-compose/docker-compose-devmode.yml
install/docker-compose/docker-compose-with-proxy.yml
install/docker-compose/docker-compose.yml
install/docker-compose/kafdrop-addon.yml
install/docker-compose/nats-addon.yml
install/docker-compose/rabbitmq-addon.yml
install/kubernetes/microcks/values.yaml
install/podman-compose/microcks-template-async-addon.yml
install/podman-compose/microcks-template-devmode.yml
install/podman-compose/microcks-template.yml
testsuite/install-helm.sh

This script attempts streamline the installation process for helm with minikube.
If it's agreed that this approach is feasible, I'll add option for async feature.
cc @lbroudoux

feat: add script for helm installation

---

.github/workflows/microcks-health-check.yml

feat: add config for healthcheck workflow

---

testsuite/check-health.sh

feat: cover helm in check-health script

---

testsuite/api-tests.js
testsuite/commons.js

feat: add tests for sample APIs

---

.github/workflows/health-check.yml
testsuite/check-health.sh
testsuite/install-helm.sh

feat: enable health-checks for helm in workflow

---

install/kubernetes/microcks/templates/secret.yaml

Added missing common annotations block on secrets in helm chart.
Fixes #1640

Fix missing common annotations block in helm chart

---

webapp/src/main/java/io/github/microcks/listener/DailyStatisticsFeeder.java
webapp/src/main/java/io/github/microcks/repository/CustomDailyStatisticRepository.java
webapp/src/main/java/io/github/microcks/repository/DailyStatisticRepositoryImpl.java
webapp/src/test/java/io/github/microcks/listener/DailyStatisticsFeederTest.java

- The DailyStatisticsFeeder does a lot of requests to the database. This PR aims to batch thoses requests

Perf/use batching for DailyStatisticsFeeder 

---

webapp/src/main/java/io/github/microcks/util/script/JsScriptEngineBinder.java
webapp/src/test/java/io/github/microcks/util/script/JsScriptEngineBinderTest.java
webapp/src/test/java/io/github/microcks/util/script/TestFetchController.java

Testing of Json responses(I thought they where not working :sweat_smile: ) and more principled exceptions.
Fix #1692

feat: more principled JS fetch and tests

---

webapp/src/main/java/io/github/microcks/util/grpc/ProtobufImporter.java
webapp/src/main/java/io/github/microcks/util/script/MockRequest.java

**- Refactored `ProtobufImporter` to reduce **Sonar-reported Cognitive Complexity**.**
- Extracted methods to simplify nested conditions and improve readability.
- Replaced duplicated string literal `"package "` with a defined constant to follow **Sonar best practices**.
**- Refactored `MockRequest` constructor to reduce **Sonar-reported Cognitive Complexity** (from 66 to below 15).**
- Extracted helper methods for locale, headers, parameters, attributes, session, and user principal handling.
- Simplified nested conditions and reduced method size for better readability and maintainability.
- Verified functionality remains unchanged by running existing tests.
- Confirmed Sonar-reported issues are resolved.
Resolves #1714
**Sonar Report (before):**
**Sonar Report (After):**

Refactor ProtobufImporter & MockRequest: Reduce Sonar-reported Cognitive Complexity (Resolves #1714)

---

webapp/src/main/java/io/github/microcks/config/OtelAutoConfigurationCustomizerProvider.java
webapp/src/main/java/io/github/microcks/service/SpanStorageService.java
webapp/src/main/java/io/github/microcks/util/otel/CustomExplainTraceProcessor.java
webapp/src/main/java/io/github/microcks/util/tracing/CommonEvents.java
webapp/src/main/java/io/github/microcks/util/tracing/TraceUtil.java
webapp/src/main/java/io/github/microcks/web/RestController.java
webapp/src/main/java/io/github/microcks/web/RestInvocationProcessor.java
webapp/src/main/java/io/github/microcks/web/TracingController.java
webapp/src/test/java/io/github/microcks/service/SpanStorageServiceTest.java
webapp/src/test/java/io/github/microcks/util/TraceUtilTest.java
webapp/src/test/java/io/github/microcks/util/otel/CustomExplainTraceProcessorTest.java
webapp/src/test/java/io/github/microcks/web/TracingControllerIT.java

This PR adds the basic tracing implementation into microcks which contains the 'Processing','Storage' and query.
This PR does not contain the SSE endpoint but the prequisites for this endpoint
#1728

feat: add basic tracing storage and query

---

webapp/src/main/java/io/github/microcks/util/script/HttpHeadersStringToStringsMap.java

**Description**
Part of https://github.com/microcks/microcks/issues/1714.

chore: removed unused import in HttpHeadersStringToStringsMap.java

---

webapp/src/main/webapp/src/app/components/collapsible-live-traces/collapsible-live-traces.component.css
webapp/src/main/webapp/src/app/components/collapsible-live-traces/collapsible-live-traces.component.html
webapp/src/main/webapp/src/app/components/collapsible-live-traces/collapsible-live-traces.component.ts
webapp/src/main/webapp/src/app/pages/services/{serviceId}/_components/exchanges-tabset/exchanges-tabset.component.css
webapp/src/main/webapp/src/app/pages/services/{serviceId}/_components/exchanges-tabset/exchanges-tabset.component.html
webapp/src/main/webapp/src/app/pages/services/{serviceId}/service-detail.page.css
webapp/src/main/webapp/src/app/pages/services/{serviceId}/service-detail.page.html
webapp/src/main/webapp/src/app/pages/services/{serviceId}/service-detail.page.ts

- This PR adds the live traces component to the service page
https://github.com/user-attachments/assets/d1584056-5b4f-493f-9c79-9c7d97575099
#1728

feat: add live traces component to service detail
